name: CI

on:
  push:
    # Always trigger CI on push
  pull_request:
    branches: [ $default-branch ]


jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        buildtype:
          - Debug
          - Release
        include:
          - os: ubuntu-latest
            buildtype: Coverage
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build and Test
      run: |
        if [[ "${{ matrix.buildtype }}" == "Coverage" ]]; then
          ctest -S cmake/CI.CTestScript.cmake --output-on-failure -VV -DCTEST_SITE=GitHub -DCTEST_BUILD_NAME="${{ matrix.os }}-${{ matrix.buildtype }}"
        else
          mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} .. && make -j4 && ctest -VV .
        fi

    - name: Publish Code Coverage
      if: ${{ matrix.buildtype == 'Coverage' }}
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{ github.workspace }}/buildCI/Testing/*/CoverageLog-0.xml:cobertura
