name: CI

on:
  push:
    # Always trigger CI on push
  pull_request:
    branches: [ $default-branch ]


jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        buildtype:
          - Debug
          - Release
        include:
          - os: ubuntu-latest
            buildtype: Coverage
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build and Test
      if: ${{ matrix.buildtype != 'Coverage' }}
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }}
        cmake --build build --config ${{ matrix.buildtype }}
        cd build
        [[ ${{ matrix.os }} == windows* ]] && cd ${{ matrix.buildtype }}
        ctest -VV

    - name: Build and Test for Code Coverage
      if: ${{ matrix.buildtype == 'Coverage' }}
      run: |
        ctest -S cmake/CI.CTestScript.cmake --output-on-failure -V -DCTEST_SITE=GitHub -DCTEST_BUILD_NAME="${{ matrix.os }}-${{ matrix.buildtype }}"

    - name: Publish Code Coverage
      if: ${{ matrix.buildtype == 'Coverage' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
